version: '3.8'

services:
  backend:
    image: wielandseb/concertjournal:api-v4
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./DB_production:/app/DB
    environment:
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network

  frontend:
    image: wielandseb/concertjournal:frontend-v3
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge