version: '3.8'

services:
  backend:
    image: wielandseb/concertjournal:api-v8
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./DB_production:/app/DB
    environment:
      - JWT_SECRET=${JWT_SECRET}

  frontend:
    image: wielandseb/concertjournal:frontend-v6
    container_name: frontend
    ports:
      - "3010:3000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

