version: '3.8'

services:
  backend:
    image: wielandseb/concertjournal:api-v9
#    build:
#      context: ./../ConcertJournalAPI
    container_name: backend
    ports:
      - "7070:8080"
    volumes:
      - ./config:/app/config
      - ./DB:/app/DB
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_CONFIG_LOCATION=file:/app/config/application.properties

  frontend:
    image: wielandseb/concertjournal:frontend-v15
#    build:
#      context: ./../ConcertJournalApp
    container_name: frontend
    ports:
      - "3020:3000"
    volumes:
        - ./config.json:/app/build/config.json

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
