global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'concertjournalAPI'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['traefik:80']
  - job_name: 'traefik'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'traefik:8899' ]
